### ISSUE TITLE
Cannot run

### ISSUE THREAD

**Issue by GXcells** [karanjot21/Photogenic#1]
Hi, I really wanted to try this code but I cannot make it run.

If  I run the app.py and I go to the adress given but I get only a page with "jO" written. ( I also get a windows defender warning that blocks python)

The main.py script does not seem to work. Nothing is happening when I run it.

Is there a way to run the script without using the app?

Thanks in advance

**Comment by GXcells** [comment]
When trying main.py I get the following error
Traceback (most recent call last):
  File "C:\Users\photogenic\Photogenic\main.py", line 419, in <module>
    main()
  File "C:\Users\photogenic\Photogenic\main.py", line 382, in main
    out = main_main(images)
  File "C:\Users\photogenic\Photogenic\main.py", line 329, in main_main
    snew = dlibSubjects(image, s)
  File "C:\Users\photogenic\Photogenic\main.py", line 74, in dlibSubjects
  File "C:\Users\photogenic\Photogenic\main.py", line 51, in face_detection_dlib
    return faces[0]
IndexError

**Comment by karancode-singh** [comment]
For your app related question, please run using main.py.

Regarding `indexError` - are you trying with the sample images or feeding your own image? The reason for the error is that no faces were recognized. Please try running with sample images first to make sure that all configurations are in place and faces are indeed detected. Then you may try with your own images.

Also note that I worked on this project more than 5 years ago so I might not be able to help much if something doesn't work anymore.

**Comment by GXcells** [comment]
Yes I used your sample images.
The problem comes from dlib. If I switch dlib to "False" then it works.

I have problem now with the face detector which fails to find all faces on most pictures that I use. I will try to implement resnet50 instead of the openCV face detection.

**Comment by karancode-singh** [comment]
Sorry, missed your comment. Did the use of resnet50 help? If yes, do you mind raising a PR with your changes for future users?

**Comment by GXcells** [comment]
Unfortunately I did not manage to do it.
